---
title: "absolute_number_deaths"
format: html
editor: visual
---

## Quarto

```{r}
library(dplyr)
library(readr)
devtools::load_all("..")
total_burden_nvss_2002_nation <- read_data("../data/09_total_burden_parsed/nation/nvss/total_burden_nvss_2002.csv")
```

```{r}
total_burden_nvss_2002_nation <- total_burden_nvss_2002_nation %>%
  filter(Gender.Code == "A"   & rural_urban_class == "666") %>% filter(Education == 666 & Race == "All" & rural_urban_class == "666" & label_cause == "all-cause")
```

```{r}
sum(total_burden_nvss_2002_nation$Deaths)
```

```{r}
total_burden_nvss_2002_county <- read_data("../data/09_total_burden_parsed/county/nvss/total_burden_nvss_2002.csv")
```

```{r}
total_burden_nvss_2002_county <- total_burden_nvss_2002_county %>%
  filter(Gender.Code == "A"  ) %>% filter(Education == 666 & Race == "All" & label_cause == "all-cause") #& rural_urban_class == "666" 
```

```{r}
sum(total_burden_nvss_2002_county$Deaths)
```

```{r}
total_burden_age_adjusted_2002 <- read_data("../data/16_sum_higher_geog_level_total/nation/total_burden_age_adjusted_2002.csv")
```

```{r}
total_burden_age_adjusted_2002 <- total_burden_age_adjusted_2002 %>%
  filter(Gender.Code == "A"  ) %>% filter(Education == 666 & Race == "All" & label_cause == "all-cause" & svi_bin == "666" & rural_urban_class == "666" ) # 
total_burden_age_adjusted_2002
```

```{r}
all_burd <- read_data("../data/17_summary/all_burd.csv")
```

```{r}
all_burd <- all_burd %>%
 filter(Education == 666 & Ethnicity == "All, All Origins" & rural_urban_class == "All" & svi_bin == "666" & measure2 == "age-adjusted rate per 100,000") #
all_burd
```
