---
title: "us_map"
author: "Daniel"
date: '2022-10-11'
output: html_document
---
```{r, echo = F}
library(dplyr)
library(usmap)
library(data.table)
library(ggplot2)
library(ggpubr)
```

```{r}
scenarioI <- "real"
methodI <- "di_gee"
  
summaryDir <- here::here("data/15_summary") 
figuresDir <- here::here("data/16_figures") 
```

lead attributable burden
```{r}
file_list <- list.files(file.path(summaryDir, "county"))
file_list <- file.path(summaryDir, "county", file_list[grepl("attr_bur", file_list)])
attr_burd <- lapply(file_list, fread) %>% rbindlist(use.names = TRUE)

```

```{r}
attr_burd <- attr_burd %>%
  filter(
    Gender.Code == "All genders" & measure1 == "Deaths" & measure2 == "age-adjusted rate per 100,000" & method == "di_gee" &
      attr == "attributable" &
      source == "National Vital Statistics System" & rural_urban_class == "All" & agr_by == "county" &
       scenario == "real" & Year %in% 2016 &
      Education == 666
  )
```


separate 
```{r}
unique(attr_burd$Ethnicity)
attr_burd_sub1 <- attr_burd %>%
  filter(Ethnicity %in% c("Black American", "NH White", "Hispanic or Latino White", "American Indian or Alaska Native", "Asian or Pacific Islander") &
    Education == 666 & Ethnicity != "All, All Origins" & rural_urban_class == "All" ) 
```

```{r}
breaks = c(1,2.5,5,7.5)
ggplot(attr_burd_sub1, aes(x=mean)) + 
  geom_histogram() +#binwidth=1
  geom_vline(xintercept=breaks, color = "red") +
 facet_wrap(~ Ethnicity, nrow = 2)
```

```{r}
name = "Percentage of all-cause mortality
attributable to PM2.5"
map1 <-  plot_usmap(data = attr_burd_sub1 %>% rename(state = Region), values = "mean", color = "white") +
 #scale_fill_viridis_b(name = name#, 
                      #breaks = c(5, 10, 15, 20, 40, 60), 
                      #label = c(5, 10, 15, 20, 40, 60)
#                      ) +
  scale_fill_viridis_c(name = name)+
 theme(legend.position = c(.85, .1), legend.justification = c(1, 0)) +
 facet_wrap(~ Ethnicity, ncol = 2) +                                                                
  theme(strip.text.x = element_text(size = 12)) # Change font size

map1
```

```{r}
ggsave(file.path(figuresDir, paste0(methodI,"-",scenarioI), "figure4.png"), dpi = 300, map1, height = 12, width = 8)
```

