---
title: "us_map"
author: "Daniel"
date: '2022-10-11'
output: html_document
---
```{r, echo = F}
library(dplyr)
library(usmap)
library(data.table)
library(ggplot2)
library(ggpubr)

suppressMessages({
  pkgload::load_all()
})

```

```{r}
scenarioI <- "real"
methodI <- "di_gee"
  
summaryDir <- here::here("data/17_summary") 
figuresDir <- here::here("data/18_figures") 
states <- read.csv(here::here("data/tmp/states.csv"))

```

lead attributable burden
```{r}
file_list <- list.files(summaryDir)
file_list <- file.path(summaryDir, file_list[grepl("attr_bur", file_list)])

attr_burd <- lapply(file_list, read_data) %>% rbindlist(use.names = TRUE, fill = TRUE)
```

filter out relevant data
```{r}
unique(attr_burd$measure3)
attr_burd <- attr_burd %>% 
  filter(attr == "attributable" & scenario == scenarioI & Region != "United States") %>%
  filter(
    Year == 2016 &
    Gender.Code == "All genders" & measure1 == "Deaths" & measure2 == "age-adjusted rate per 100,000" &
    source == "National Vital Statistics System" & 
    method == methodI &
      svi_bin == "All" &
      rural_urban_class == "All" &
      svi_bin1 == "All" &
      svi_bin2 == "All" &
      svi_bin3 == "All" &
      svi_bin4 == "All" & 
      min_age == 25
    ) 

attr_burd <- attr_burd %>%
  filter(Ethnicity %in% c("Black American", "NH White", "Hispanic or Latino White", "American Indian or Alaska Native", "Asian or Pacific Islander") &
    Education == 666 & Ethnicity != "All, All Origins" & rural_urban_class == "All" )

```

separate 
```{r}
attr_burd_sub1 <- attr_burd %>% filter(measure3 == "prop. of overall burden")
attr_burd_sub2 <- attr_burd %>% filter(measure3 == "value") 
nrow(attr_burd_sub2)
```

```{r}
breaks1 = c(0,2.5,5,7.5)
#breaks1 = c(0.1, 1, 10)
ggplot(attr_burd_sub1, aes(x=mean)) + 
  geom_histogram() +#binwidth=1
  geom_vline(xintercept=breaks1, color = "red") +
 facet_wrap(~ Ethnicity, nrow = 2)
```

```{r}
breaks2 = c(1,10,100)
ggplot(attr_burd_sub2, aes(x=mean)) + 
  geom_histogram() +#binwidth=1
  geom_vline(xintercept=breaks2, color = "red") +
  facet_wrap(~ Ethnicity, nrow = 2)
```
```{r}
attr_burd_sub1_plotting <- attr_burd_sub1 %>%
  rowwise() %>%
  mutate(fips = states$STATEFP[as.numeric(Region)]) %>%
  mutate(fips = sprintf("%02d", as.numeric(fips)))

attr_burd_sub1_plotting <- attr_burd_sub1_plotting %>%
  mutate(Ethnicity = as.factor(Ethnicity))
```

```{r}
name = "Percentage of all-cause mortality
attributable to PM2.5"
```


```{r}

map1 <-  plot_usmap(data = attr_burd_sub1_plotting, regions = "states", values = "mean", color = "white") +
 #scale_fill_viridis_b(name = name#, 
                      #breaks = c(5, 10, 15, 20, 40, 60), 
                      #label = c(5, 10, 15, 20, 40, 60)
#                      ) +
  scale_fill_viridis_c(#breaks = breaks1, labels = breaks1,
                       #trans = scales::pseudo_log_trans(sigma = 0.001),
                       name = name) +
  #scale_fill_viridis_c()+
  theme(legend.position.inside = c(0.65, .1) # .inside
        , text = element_text(size=10)) +
 #theme(legend.position.inside = c(1, .1), legend.justification = c(1, 0),
#        text = element_text(size=16)) +
 facet_wrap(~ Ethnicity, ncol = 2)                                                        # Change font size

map1
```

```{r}
ggsave(file.path(figuresDir, paste0(methodI,"-",scenarioI,"-25"), "figure4.png"), dpi = 300, map1, height = 12, width = 8)
ggsave(file.path(figuresDir, paste0(methodI,"-",scenarioI,"-25"), "figure4.pdf"), dpi = 300, map1, height = 12, width = 8)
```
