---
title: "within_county_pm_variation"
author: "Daniel"
date: '2022-10-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, include=FALSE}
library(dplyr)
library(magrittr)
library(data.table)
library(ggplot2)
library(tidyverse)

options(bitmapType ="cairo")
theme_set(theme_classic(base_family = "Helvetica"))
```

```{r}
scenarioI <- "real"
methodI <- "di_gee"
summaryDir <- here::here("data/17_summary") 
figuresDir <- here::here("data/16_figures") 
```

## exposure

```{r}
pm_summ <- fread(file.path(summaryDir, "pm_summary.csv"))
rm(file_list)
```

```{r}
pm_summ <- pm_summ %>%
  filter(Gender.Code == "All genders" & Region == "United States" & pm_metric == "mean" & scenario == scenarioI)
pm_summ1 <- pm_summ %>% filter(Education == 666 & Ethnicity == "All, All Origins" & rural_urban_class == "All")

```

```{r}
g1 <- ggplot(pm_summ1, aes(x = Year, y = value))+
    geom_line(size = 1.5) +
    xlab("Year") +
  ylab(expression(paste("mean PM2.5 exposure (", mu, g, "/", m^3,")", sep=""))) +
  theme(text = element_text(size=16))
g1
```
```{r}
ggsave(file.path(figuresDir, paste0(methodI, "-", scenarioI), "figureS1_overall_population.png"), dpi = 300, g1, height = 4, width = 8)
```

## all-cause burden
```{r}
all_burden <- fread(file.path(summaryDir, "all_burd.csv"))
```

```{r}
all_burden <- all_burden %>%
  filter(Gender.Code == "All genders" & measure1 == "Deaths" & measure2 == "age-adjusted rate per 100,000" &
    source == "National Vital Statistics System" & Region == "United States" & svi_bin == "666")

all_burden <- all_burden %>% filter(Education == 666 & Ethnicity == "All, All Origins" & rural_urban_class == "All")

```

```{r}
g2 <- ggplot(all_burden, aes(x = Year, y = overall_value)) +
    geom_line(size = 1.5) +
    xlab("Year") +
    ylab("Age-adjusted mortality\n per 100,000 from all causes")+
  theme(text = element_text(size=16))
g2
```

```{r}
ggsave(file.path(figuresDir, paste0(methodI, "-", scenarioI), "figure_S_all_causes_overall.png"), dpi = 300, g2, height = 4, width = 8)

```

## attributable burden
```{r}
file_list <- list.files(summaryDir)
file_list <- file.path(summaryDir, file_list[grepl("attr_bur", file_list)])
attr_burd <- lapply(file_list, fread) %>% rbindlist(use.names = TRUE)
```

```{r}
attr_burd <- attr_burd %>%
  filter(Gender.Code == "All genders" & measure1 == "Deaths" & measure2 == "age-adjusted rate per 100,000"&
           source == "National Vital Statistics System"& scenario == scenarioI& method == methodI )
attr_burd <- attr_burd %>% filter(agr_by == "nation" & Education == 666 & Ethnicity == "All, All Origins" & measure3 %in% c("value","prop. of overall burden") & rural_urban_class == "All")

attr_burd <- attr_burd %>%
  filter(min_age == 25 & max_age == 150)
```

