---
title: "within_county_pm_variation"
author: "Daniel"
date: '2022-10-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, include=FALSE}
library(dplyr)
library(magrittr)
library(data.table)
library(ggplot2)


options(bitmapType ="cairo")
theme_set(theme_classic(base_family = "Helvetica"))
```

```{r}
scenarioI <- "real"
methodI <- "di_gee"
summaryDir <- here::here("data/17_summary") 
figuresDir <- here::here("data/18_figures") 
```

## exposure

```{r}
pm_summ <- fread(file.path(summaryDir, "pm_summary.csv"))
```

```{r}
pm_summ <- pm_summ %>%
  filter(Gender.Code == "All genders" & Region == "United States" & pm_metric == "mean" & scenario == scenarioI)
pm_summ <- pm_summ %>% filter(svi_bin == "All" & svi_bin1 == "All" & svi_bin2 == "All" & svi_bin3 == "All" & svi_bin4 == "All" & min_age == 25)
pm_summ1 <- pm_summ %>% filter(Education == 666 & Ethnicity == "All, All Origins" & rural_urban_class == "All")
```

```{r}
g1 <- plot_df(pm_summ1)

g1 <- ggplot(pm_summ1, aes(x = Year, y = value))+
    #geom_line(linewidth = 1.5) +
  geom_ribbon(aes(ymin = mean_lower, ymax = mean_upper),  show.legend = FALSE) +
    xlab("Year") + #linetype = 2, alpha = 0,
  ylim(0,NA)+
  ylab(expression(paste("Mean PM2.5 exposure (", mu, g, "/", m^3,")", sep=""))) +
  theme(text = element_text(size=16))
g1
```

```{r}
ggsave(file.path(figuresDir, paste0(methodI, "-", scenarioI), "figureS1_overall_population.png"), dpi = 300, g1, height = 4, width = 8)
```

## all-cause burden
```{r}
all_burden <- fread(file.path(summaryDir, "all_burd.csv"))
all_burden <- all_burden %>% filter(min_age == 25)
```

```{r}
all_burden <- all_burden %>%
  filter(Gender.Code == "All genders" & measure1 == "Deaths" & measure2 == "age-adjusted rate per 100,000" &
    source == "National Vital Statistics System" & Region == "United States")

all_burden <- all_burden %>% filter(Education == 666 & Ethnicity == "All, All Origins" & rural_urban_class == "All")

```

```{r}
g2 <- ggplot(all_burden, aes(x = Year, y = value)) +
    geom_line(linewidth = 1.5) +
    xlab("Year") +
    ylab("Age-adjusted mortality\n per 100,000 from all causes")+
  theme(text = element_text(size=16))
g2
```

```{r}
ggsave(file.path(figuresDir, paste0(methodI, "-", scenarioI), "figureS2_all_causes_overall.png"), dpi = 300, g2, height = 4, width = 8)
```

